// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhtt4YYUMvcNPwwwo_7AIFnFyJv93XT0',
    appId: '1:100784575969:web:974e59fa36dc3acb72eea0',
    messagingSenderId: '100784575969',
    projectId: 'mealplanet-8d459',
    authDomain: 'mealplanet-8d459.firebaseapp.com',
    storageBucket: 'mealplanet-8d459.appspot.com',
    measurementId: 'G-EE79Y8EC7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvqnOzQ_9W_WBlfh94E_a6IjvPkLaWiU',
    appId: '1:100784575969:android:3c2310f93dd2ee0772eea0',
    messagingSenderId: '100784575969',
    projectId: 'mealplanet-8d459',
    storageBucket: 'mealplanet-8d459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCYeUU6YEn7HMNmIU7-c_t7vGtjEw4iso',
    appId: '1:100784575969:ios:6719c51e1479f6d272eea0',
    messagingSenderId: '100784575969',
    projectId: 'mealplanet-8d459',
    storageBucket: 'mealplanet-8d459.appspot.com',
    androidClientId: '100784575969-9m5tesohe0gibigrv4snale7g2988s1i.apps.googleusercontent.com',
    iosClientId: '100784575969-95o1nblrhbig3n3rd9fkjnsf6am2cm54.apps.googleusercontent.com',
    iosBundleId: 'com.mealplanet.mobile.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCYeUU6YEn7HMNmIU7-c_t7vGtjEw4iso',
    appId: '1:100784575969:ios:2e9a312eb46377fd72eea0',
    messagingSenderId: '100784575969',
    projectId: 'mealplanet-8d459',
    storageBucket: 'mealplanet-8d459.appspot.com',
    androidClientId: '100784575969-9m5tesohe0gibigrv4snale7g2988s1i.apps.googleusercontent.com',
    iosClientId: '100784575969-ole0r5bs1ug2h8okduvl0a0hell5rsdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanet.RunnerTests',
  );
}
